apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-param-result-
spec:
  entrypoint: loop-param-result-example
  templates:
  - name: loop-param-result-example
    steps:
    - - name: generate
        template: gen-number-list
    - - name: sleep
        template: sleep-n-sec
        arguments:
          parameters:
          - name: tiktok
            value: "{{item}}"
        withParam: "{{steps.generate.outputs.result}}" # ここでoutputsのリストを展開している
  - name: gen-number-list
    container:
      image: scraper:latest
      command: [python]
      args: [app.py]
      imagePullPolicy: IfNotPresent # ローカルDockerイメージを使うなら、これが必要
  - name: sleep-n-sec
    inputs:
      parameters:
      - name: tiktok # ここに展開された値が渡されてくる
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo {{inputs.parameters.tiktok}};"]