apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: tiktok-platform-workflow
spec:
  entrypoint: tiktok-platform-entrypoint
  templates:
  - name: tiktok-platform-entrypoint
    steps:
    - - name: scraper
        template: scraper
    - - name: single-tiktok-processer
        template: single-tiktok-processer
        arguments:
          parameters:
          - name: tiktok
            value: "{{item}}"
        withParam: "{{steps.scraper.outputs.result}}"
  - name: scraper
    container:
      image: scraper:latest
      command: [python]
      args: [app.py]
      imagePullPolicy: IfNotPresent
  - name: single-tiktok-processer
    inputs:
      parameters:
      - name: tiktok
    steps:
      - - name: transfer
          template: transfer
          arguments:
            parameters:
            - name: tiktok
              value: "{{inputs.parameters.tiktok}}"
      - - name: storer
          template: storer
          arguments:
            parameters:
            - name: tiktok
              value: "{{steps.transfer.outputs.result}}"
  - name: transfer
    inputs:
      parameters:
      - name: tiktok
    container:
      image: transfer:latest
      command: [python]
      args: [app.py]
      imagePullPolicy: IfNotPresent
      env:
      - name: INPUT_DATA
        value: "{{inputs.parameters.tiktok}}"
  - name: storer
    inputs:
      parameters:
      - name: tiktok
    container:
      image: storer:latest
      command: [./storer]
      imagePullPolicy: IfNotPresent
      env:
      - name: INPUT_DATA
        value: "{{inputs.parameters.tiktok}}"