apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: tiktok-platform-workflow
spec:
  entrypoint: tiktok-platform-entrypoint
  templates:
  - name: tiktok-platform-entrypoint
    steps:
    - - name: scraper
        template: scraper
    - - name: single-tiktok-processer
        template: single-tiktok-processer
        arguments:
          parameters:
          - name: tiktok
            value: "{{item}}"
        withParam: "{{steps.scraper.outputs.result}}"
  - name: scraper
    retryStrategy:
      limit: "2"
      retryPolicy: "Always"
    container:
      image: "{{workflow.parameters.docker_scraper}}"
      command: [python]
      args: [app.py]
      imagePullPolicy: IfNotPresent
      env:
      - name: USER_NAME
        value: "{{workflow.parameters.tiktok_user_name}}"
      - name: COUNT
        value: "{{workflow.parameters.tiktok_user_count}}"
      - name: CUSTOM_VERIFY_FP
        value: "{{workflow.parameters.tiktok_custom_verify_fp}}"
  - name: single-tiktok-processer
    inputs:
      parameters:
      - name: tiktok
    steps:
      - - name: transfer
          template: transfer
          arguments:
            parameters:
            - name: tiktok
              value: "{{inputs.parameters.tiktok}}"
      - - name: storer
          template: storer
          arguments:
            parameters:
            - name: tiktok
              value: "{{steps.transfer.outputs.result}}"
  - name: transfer
    inputs:
      parameters:
      - name: tiktok
    container:
      image: "{{workflow.parameters.docker_transfer}}"
      command: [python]
      args: [app.py]
      imagePullPolicy: IfNotPresent
      env:
      - name: INPUT_DATA
        value: "{{inputs.parameters.tiktok}}"
      - name: GCP_PROJECT
        value: "{{workflow.parameters.tiktok_gcp_project}}"
      - name: CUSTOM_VERIFY_FP
        value: "{{workflow.parameters.tiktok_custom_verify_fp}}"
  - name: storer
    inputs:
      parameters:
      - name: tiktok
    container:
      image: "{{workflow.parameters.docker_storer}}"
      command: [./storer]
      imagePullPolicy: IfNotPresent
      env:
      - name: INPUT_DATA
        value: "{{inputs.parameters.tiktok}}"